Repository schergen-org/JAWG, pull requests merged in 2025-03, with the labels that each got.

#12 Fix Typo
  README.md
Labels: bug

#10 3 basic json type linking
  project-amsterdam/src/App.tsx
  project-amsterdam/src/types/Schema.ts
  project-amsterdam/src/types/blocks/ExperienceBlock.ts
  project-amsterdam/src/types/blocks/ProjectBlock.ts
  project-amsterdam/src/types/blocks/TextBlock.ts
Labels: enhancement

#13 6 enforce linting on commits and pull requests
  project-amsterdam/.husky/pre-commit
  project-amsterdam/package.json
Labels: projekt steup
